# builder image
FROM golang:1.21 as builder

WORKDIR /build

COPY go.mod ../
COPY go.sum ../
RUN go mod download

COPY server .
COPY proto ../proto

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o app .

# generate clean, final image for end users
# FROM debian:buster-slim
# RUN apt-get update && apt-get install -y ca-certificates
FROM gcr.io/distroless/base-debian11
COPY --from=builder /build/app .

# executable
EXPOSE 8080
ENTRYPOINT [ "./app" ]